### Array creation and attributes using NumPy

In [1]:
# 1. Import the Numpy library with the alias 'np'.
import numpy as np

In [3]:
# 2. Create a 1D numpy array from the python list [1, 2, 3, 4, 5].
array_id = np.array([1, 2, 3, 4, 5])
print(array_id)

[1 2 3 4 5]


In [16]:
# 3. Create a 1D arrays of 10 zeros.
array_zeros = np.zeros(10, dtype=int)
print(array_zeros)

[0 0 0 0 0 0 0 0 0 0]


In [13]:
# 4. Create a 3 x 3 array filled with ones.
array_ones = np.ones((3, 3), dtype=int)
print(array_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# 5. Create an array of all even integers from 10 to 50.
array_even = np.arange(10, 51, 2)
print(array_even)
# arange is as range in python, but return an array.


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [19]:
# 6. Create a 3X3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 7. Create 4x4 identity matrix.
identity_matrix = np.eye(4, dtype=int)
print(identity_matrix)
# np.eye is used to create a 2D array with ones on the diagonal and zeros elsewhere.

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# 8. Create an array of 5 numbers evenly spaced between 0 and 1.
array_linspace = np.linspace(0, 1, 5)
print(array_linspace)
# linspace is used to control number of elements in the array.

[0.   0.25 0.5  0.75 1.  ]


In [23]:
# 9. Create a 3x4 array filled with random numbers between 0 and 1.
random_array = np.random.rand(3, 4)
print(random_array)  

[[0.59188404 0.38132965 0.7508258  0.03925646]
 [0.74829948 0.16012904 0.05715558 0.18332562]
 [0.53103049 0.63440179 0.35763802 0.06007654]]


In [26]:
# 10. Create a 5x5 array with random integers from 1 to 100.
random_array = np.random.randint(1, 101, size=(5, 5))
print(random_array) 

[[96 11 76 16 57]
 [61 43 27 57  2]
 [65 63 21 37 15]
 [86 30 93 88 36]
 [85 34 45 41 46]]


In [28]:
# 11. Given the array arr = np.arange(25).reshape(5, 5), find its shape. 
arr = np.arange(25).reshape(5, 5)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [31]:
# 12. for the same array, find its data type.
print(arr.dtype)

int32


In [32]:
# 13. For the same array arr, find the total number of elements.
print(arr.size)

25


In [33]:
# 14. Create the array [1, 2, 3] but make sure its data type is float. 
array_float = np.array([1, 2, 3], dtype=float)
print(array_float)

[1. 2. 3.]


In [ ]:
# 15. Convert the data type of an existing integer array to float.
array_int = np.array([1, 2, 3, 4, 5])
array_converted = array_int.astype(float)
print(array_converted)

[1. 2. 3. 4. 5.]


### Indexing & Slicing (Accessing Your Data)

In [6]:
arr_1d = np.arange(10)
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# 16. From arr_1d, get the first element.
print(arr_1d[0]) 

0


In [8]:
# 17. From arr_1d, get the last element. 
print(arr_1d[-1])

9


In [9]:
# 18. From arr_1d, get the elements from index 2 up to index 5.
print(arr_1d[2:6]) 

[2 3 4 5]


In [10]:
# 19. From arr_1d, get all elements in reverse order.
print(arr_1d[::-1]) 

[9 8 7 6 5 4 3 2 1 0]


In [11]:
# 20. From arr_2d, get the element at row 1, column 2 (which is 6). 
print(arr_2d[1, 2])

6


In [12]:
# 21. From arr_2d, get the entire first row [1, 2, 3].
print(arr_2d[0]) 

[1 2 3]


In [13]:
# 22. From arr_2d, get the entire second column [2, 5, 8].
print(arr_2d[:, 1])

[2 5 8]


In [14]:
# 23. From arr_2d, extract the sub-array [[1, 2], [4, 5]]. 
print(arr_2d[0:2, 0:2])

[[1 2]
 [4 5]]


In [ ]:
# 24. Create a boolean mask to find all numbers in arr_1d that are greater than 5. 
mask = arr_1d > 5
print(mask)

[6 7 8 9]
[False False False False False False  True  True  True  True]


In [20]:
# 25. Use the boolean mask from the previous question to select the actual numbers from arr_1d. 
print(arr_1d[mask])

[6 7 8 9]


In [21]:
# 26. In one line, select all numbers from arr_2d that are odd.
print(arr_2d[arr_2d % 2 == 1]) 

[1 3 5 7 9]


In [22]:
# 27. In arr_1d, replace all values greater than 5 with the value 0. 
arr_1d[arr_1d > 5] = 0
print(arr_1d)

[0 1 2 3 4 5 0 0 0 0]


In [33]:
# 28. From arr_1d, select the elements at indices 1, 3, and 7.
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(arr_1d[[1, 3, 7]])


[20 40 80]


In [36]:
# 29. From arr_2d, select the first and third rows. 
print(arr_2d[[0, 2], :])

[[1 2 3]
 [7 8 9]]


In [38]:
"""30. What is the difference between a slice (view) and a fancy index (copy)? Modify a slice of 
arr_1d and see if the original changes."""
arr_1d = np.array([10, 20, 30, 40, 50])
slice_arr = arr_1d[1:4]  # This creates a view (slice)
facny_arr = arr_1d[[1, 2, 3]]  # This creates a copy (fancy index)
print("Original array:", arr_1d)
print("Slice (view):", slice_arr)
print("Fancy index (copy):", facny_arr)

Original array: [10 20 30 40 50]
Slice (view): [20 30 40]
Fancy index (copy): [20 30 40]


In [39]:
# 31. Create a copy of arr_2d and modify an element in the copy. Check if the original array is affected.
arr_2d_copy = arr_2d.copy()
arr_2d_copy[0, 0] = 99
print("Original arr_2d:\n", arr_2d)
print("Modified copy of arr_2d:\n", arr_2d_copy) 

Original arr_2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified copy of arr_2d:
 [[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [40]:
# 32. From arr_2d, get the diagonal elements [1, 5, 9]. 
print(np.diag(arr_2d))

[1 5 9]


In [56]:
# 33. Select all rows from arr_2d where the first element is less than 5.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original \n{arr_2d} \n")
print(f"less than < 5  \n{arr_2d[arr_2d[:, 0] < 5]}")

Original 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

less than < 5  
[[1 2 3]
 [4 5 6]]


In [57]:
# 34. From arr_2d, select the elements [2, 4, 9]. 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[[0, 1, 2], [1, 0, 2]])

[2 4 9]


In [58]:
# 35. Reverse the order of the rows in arr_2d.
print(arr_2d[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Mathematical & Universal Functions (UForms)

In [59]:
# 36. Add array a and b element-wise.  

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a+b)


[ 6  8 10 12]


In [60]:
# 37. Multiply array a by 3 (scalar multiplication).
print(a * 3)

[ 3  6  9 12]


In [62]:
# 38. Calculate the square of every element in array a.
print(a ** 2)
print(np.square(a)) 

[ 1  4  9 16]
[ 1  4  9 16]


In [63]:
# 39. Calculate the square root of every element in b.
print(np.sqrt(b))

[2.23606798 2.44948974 2.64575131 2.82842712]


In [64]:
# 40. Calculate the exponential (e^x) of every element in a. 
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [65]:
# 41. Find the sum of all elements in a.
print(np.sum(a))
print(sum(a))

10
10


In [68]:
# 42. Find the mean of all elements in b.
print(np.mean(b))
print(b.mean()) 

6.5
6.5


In [70]:
# 43. Find the maximum value in a.
print(np.max(a))
print(max(a)) 
print(a.max())

4
4
4


In [ ]:
# 44. Find the minimum value in b.
print(np.min(b))
print(min(b)) 
print(b.min())

5
5
5


In [79]:
# 45. Given a 2D array matrix = np.arange(12).reshape(3, 4), find the sum of all its elements.
matrix = np.arange(12).reshape(3, 4)
print(matrix)
print(np.sum(matrix))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66


In [86]:
# 46. For the matrix, find the sum of each column.
matrix = np.arange(12).reshape(3, 4)
print(sum(matrix))
print(matrix.sum(axis=0))

# axis=0 → operation along rows → result per column.
# axis=1 → operation along columns → result per row.

[12 15 18 21]
[12 15 18 21]


In [ ]:
# 47. For the matrix, find the mean of each row.
matrix = np.arange(12).reshape(3, 4)
print(matrix.mean(axis=1))

[1.5 5.5 9.5]


In [89]:
# 48. For the matrix, find the minimum value in each row.
matrix = np.arange(12).reshape(3, 4)
print(matrix)
print(matrix.min(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 4 8]


In [90]:
# 49. Create a new array by finding which element is larger at each position between a and b.
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.maximum(a, b))

[5 6 7 8]


In [93]:
# 50. Round all values in the array arr_float = np.array([1.5, 2.3, 3.8]) to the nearest integer.
arr_float = np.array([1.5, 2.3, 3.8])
print(np.round(arr_float))
print(np.round(arr_float).astype(int)) 

[2. 2. 4.]
[2 2 4]


In [94]:
# 51. Calculate the standard deviation of array a.
print(np.std(a))

1.118033988749895


In [95]:
# 52. Calculate the cumulative sum of a. The result should be [1, 3, 6, 10].
print(np.cumsum(a)) 

[ 1  3  6 10]


In [97]:
# 53. Compare arrays a and b to see if they are equal element-wise.
print(np.equal(a, b)) 
print(a == b)

[False False False False]
[False False False False]


In [98]:
# 54. Check if any element in the result of a > 2 is True.
print(np.any(a > 2))

True


In [101]:
# 55. Check if all elements in b are greater than 4.
print(np.all(b > 4))

True


### Key Manipulation Techniques 

In [ ]:
# 56. Reshape the 1D array arr = np.arange(20) into a 4x5 matrix.
arr = np.arange(20)
reshaped_arr = arr.reshape(4, 5)
print(reshaped_arr) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
# 57. "Flatten" the 2D array matrix = np.array([[1,2],[3,4]]) into a 1D array.
matrix = np.array([[1, 2], [3, 4]])
flattened_arr = matrix.flatten()
print(flattened_arr)
ravel_arr = matrix.ravel()
print(ravel_arr)

[1 2 3 4]
[1 2 3 4]


### 58. What is the main difference between .ravel() and .flatten()?
View: In NumPy, a view is a way of accessing the same data in an array without creating a new copy of it.
Copy: Copies the original file and makes changes in the copied files.

Both ravel and flatten are numpy methods used to convert multi-dimensional arrays into 1d arrays, but they differ how they the result.
ravel: returns a view, more memory-efficient, Faster(no copying unless needed), Changes the result may affect the original array.
flatten: Always returns a copy, uses more memory, Slightly slower due to copying, Changes do not affect the original.
 

In [8]:
matrix = np.array([[1, 2], [3, 4]])

ravelled_arr = matrix.ravel()
flattened_arr = matrix.flatten()

ravelled_arr[0] = 99  # Modifying the ravelled array
print("Ravelled array:", ravelled_arr)

flattened_arr[0] = 88  # Modifying the flattened array
print("Flattened array:", flattened_arr)

Ravelled array: [99  2  3  4]
Flattened array: [88  2  3  4]


In [ ]:
# 59. Transpose a 3x5 matrix into a 5x3 matrix. 
matrix_3x5 = np.arange(15).reshape(3, 5)
transported_matrix = matrix_3x5.T
print(matrix_3x5)
print(transported_matrix)
# .T: The .T attribute in NumPy is shorthand for transpose. It flips the axes of an array—rows become columns and columns become rows.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [18]:
# 60. Vertically stack the arrays a = np.ones((2,3)) and b = np.zeros((2,3)).
a = np.ones((2, 3))
b = np.zeros((2, 3))
stacked_array = np.vstack((a, b))
print(a)
print(b)
print(stacked_array)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# 61. Horizontally stack the arrays a and b.
stacked_array_h = np.hstack((a, b))
print(stacked_array_h)

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [21]:
# 62. Use np.concatenate to achieve the same result as vstack with a and b. 
a = np.ones((2, 3))
b = np.zeros((2, 3))
concatenated_array = np.concatenate((a, b), axis=0)
print(concatenated_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# 63. Split the array arr = np.arange(10) into 5 equal sub-arrays. 
arr = np.arange(10)
sub_arrays = np.split(arr, 5)
print(sub_arrays)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [25]:
# 64. Split the 2D array matrix = np.arange(16).reshape(4,4) horizontally into 2 equal arrays.
matrix = np.arange(16).reshape(4, 4)
horizontally_split = np.hsplit(matrix, 2)
print(horizontally_split) 

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [26]:
# 65. Insert the value 99 at index 2 in the 1D array arr = np.array([1,2,3,4]).
arr = np.array([1, 2, 3, 4])
inserted_array = np.insert(arr, 2, 99)
print(inserted_array)

[ 1  2 99  3  4]


In [27]:
# 66. Add the value 5 to the end of array arr. 
arr = np.array([1, 2, 3, 4])
appended_arr = np.append(arr, 5)
print(appended_arr)

[1 2 3 4 5]


In [28]:
# 67.  Get the unique values from the array arr = np.array([1,1,2,3,3,3,4,5]).
arr = np.array([1, 1, 2, 3, 3, 3, 4, 5])
unique_values = np.unique(arr)
print(unique_values) 

[1 2 3 4 5]


In [29]:
# 68. Repeat the array [1,2,3] three times to get [1,2,3,1,2,3,1,2,3]. 
arr = np.array([1, 2, 3])
print(np.tile(arr, 3))

[1 2 3 1 2 3 1 2 3]


In [30]:
# 69. Repeat each element of [1,2,3] three times to get [1,1,1,2,2,2,3,3,3].
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))

[1 1 1 2 2 2 3 3 3]


In [ ]:
# 70. Flip an array horizontally (left to right). 
arr = np.array([1, 2, 3])
print(np.flip(arr))

# np.flipud() is shorthand for flipping up-down (axis=0).
# np.fliplr() flips left-right (axis=1).

[3 2 1]


### Broadcasting & Conditional Logic 

In [33]:
# 71. Add a 1D array v = np.array([1, 2, 3]) to each row of a 2D array M = np.ones((4,3)). What is this concept called?
v = np.array([1, 2, 3])
M = np.ones((4, 3))
print(M + v) # Broadcasting 

"""Broadcasting is a powerful NumPy feature that allows arrays of different shapes to be combined in arithmetic operations. 
Instead of manually reshaping or looping, NumPy automatically expands the smaller array to match the shape of the larger one—without 
copying data unnecessarily."""

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


'Broadcasting is a powerful NumPy feature that allows arrays of different shapes to be combined in arithmetic operations. \nInstead of manually reshaping or looping, NumPy automatically expands the smaller array to match the shape of the larger one—without \ncopying data unnecessarily.'

In [34]:
# 72. Can you add a (3,3) matrix and a (3,) vector? If so, how does it work?
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])   # shape: (3:3)
v = np.array([10, 20, 30])  # shape: (3, )

print(A + v)  # Broadcasting

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [35]:
# 73. Can you add a (3,3) matrix and a (3,1) matrix? 
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])   # shape: (3:3)

B = np.array([[10],
              [20],
              [30]]) #shape: (3:1)

print(A + B)  # Broadcasting

[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [ ]:
# 74. Create a 1D array arr = np.arange(10). Use np.where to create a new array where values are 0 
# if the original value was less than 5, and the original value otherwise.
arr = np.arange(10)
print(np.where(arr < 5, 0, arr)) #np.where(condition, value_if_true, value_if_false)


[0 0 0 0 0 5 6 7 8 9]


In [37]:
# 75. Use np.where to create a new array from arr where even numbers are replaced by 0 and odd numbers by 1.
arr = np.arange(10)
print(np.where(arr % 2 == 0, 0, 1))

[0 1 0 1 0 1 0 1 0 1]


In [38]:
# 76. Create a 5x5 array of random integers. Use np.where to replace all values greater than 50 with the value 50.
arr = np.random.randint(0, 100, size=(5, 5))
print(np.where(arr > 50, 50, arr)) 

[[50 33 14 14 20]
 [50 48 31 50  5]
 [14 28 50 16  8]
 [50 50 48 44 50]
 [50 48 50 50 50]]


In [ ]:
# 77. Create a 1D array from 1 to 10. Extract all numbers that are either less than 3 or greater than 8. 
arr = np.arange(1, 11) # Creates an array [1, 2, ..., 10]
filtered_arr = arr[(arr < 3) | (arr > 8)] # OR |
print(filtered_arr)


[ 1  2  9 10]


In [41]:
# 78. What will be the result of adding a (4,1) array to a (1,5) array? 
# The result will be a (4,5) array where each element is the sum of the corresponding elements from the (4,1) and (1,5) arrays. 
# This is due to broadcasting, where the (4,1) array is broadcasted across
A = np.array([[1], 
              [2], 
              [3], 
              [4]]) # shape (4,1)
B = np.array([[10, 20, 30, 40, 50]]) # shape (1,5)

result = A + B
print(result)

[[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]
 [14 24 34 44 54]]


In [45]:
# 79. Normalize a 5x5 random matrix (subtract the mean and divide by the standard deviation). 
matrix = np.random.rand(5, 5)

# Compute the mean and standard deviation of the entire matrix.
mean = np.mean(arr)
std = np.std(arr)

#normalize: subtract mean and divide by std
normalized = (matrix - mean) / std

print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized)

Original Matrix:
 [[0.98273584 0.03506038 0.50828337 0.92635095 0.4807918 ]
 [0.05209147 0.95823492 0.2268706  0.70908309 0.00994045]
 [0.30912734 0.6919203  0.90879942 0.61133656 0.68333772]
 [0.22156362 0.70238115 0.74941854 0.2931858  0.9337336 ]
 [0.57790374 0.85431004 0.54273699 0.42413049 0.81363356]]

Normalized Matrix:
 [[ 1.85114777 -1.64794996  0.0993291   1.6429581  -0.00217789]
 [-1.58506614  1.76068311 -0.93972996  0.84074098 -1.74070014]
 [-0.63601379  0.7773709   1.57815266  0.47983193  0.74568145]
 [-0.95932491  0.81599543  0.98967138 -0.69487465  1.670217  ]
 [ 0.35638806  1.37696175  0.22654203 -0.21138818  1.22677218]]


In [46]:
# 80. Given a 1D array, create a 2D array where each row is a copy of the original array.
# Using np.tile
arr = np.array([1, 2, 3])
rows = 4

result = np.tile(arr, (rows, 1))
print(result)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
arr = np.array([1, 2, 3])
rows = 4

result = np.zeros((rows, arr.size)) + arr
print(result)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


### Statistics, Sorting, & Searching 

In [4]:
# 81. Create a 1D array of 10 random integers and sort it in ascending order. 
arr = np.random.randint(0, 11, size=10)
print(arr)
sorted_arr = np.sort(arr)
print(sorted_arr)


[ 3  5  5 10  5  5  5  3  7 10]
[ 3  3  5  5  5  5  5  7 10 10]


In [8]:
# 82. What is the difference between np.sort(arr) and arr.sort()? Explain with an example. 
# np.sort(arr) returns a sorted copy of the array, leaving the original array unchanged.
arr = np.array([3, 1, 4, 2])

# np.sort returns a new sorted array
sorted_arr = np.sort(arr)
print("Original:", arr)         # [3 1 4 2]
print("Sorted copy:", sorted_arr)  # [1 2 3 4]

# arr.sort modifies the array in-place
arr.sort()
print("Modified original:", arr)   # [1 2 3 4]

Original: [3 1 4 2]
Sorted copy: [1 2 3 4]
Modified original: [1 2 3 4]


In [ ]:
# 83. Find the indices that would sort the array arr = np.array([3, 1, 4, 2]). 
arr = np.array([3, 1, 4, 2])
argsort_arr = np.argsort(arr)
print(argsort_arr)
#It returns the indices that would sort an array. Instead of giving you the sorted values, it tells you where each value would go if you sorted the array.

[1 3 0 2]


In [10]:
# 84. Find the index of the maximum value in arr.
arr = np.array([3, 1, 4, 2])
maxargsort = np.argmax(arr)
print(maxargsort)

2


In [11]:
# 85. Find the index of the minimum value in arr.
arr = np.array([3, 1, 4, 2])
maxargsort = np.argmin(arr)
print(maxargsort) 

1


In [17]:
# 86. In a 2D array, find the index of the maximum value in each column.
arr = np.arange(12).reshape(3, 4)
max_column = np.argmax(arr, axis=0)
print(arr)
print(max_column) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[2 2 2 2]


In [21]:
# 87.  Find the unique values and their counts in the array arr = np.array([1, 2, 2, 3, 3, 3, 1]).
arr = np.array([1, 2, 2, 3, 3, 3, 1])
unique_values, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique_values)
print("Counts:", counts) 

Unique values: [1 2 3]
Counts: [2 2 3]


In [22]:
# 88. Find the common elements between two arrays a = np.array([1,2,3]) and b = np.array([2,3,4]).
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
common_elements = np.intersect1d(a, b)
print(common_elements)

[2 3]


In [23]:
# 89. Find the elements in a that are not in b.
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
unique_to_a = np.setdiff1d(a, b)
print(unique_to_a)

[1]


In [ ]:
# 90. Sort a 2D array based on its second column. Use argsort on the second column, then use the resulting indices to sort the full array. 
arr = np.array([[10, 3],
                [20, 1],
                [30, 2]])

# Step 1: Get the indices that would sort the second column
sort_indices = np.argsort(arr[:, 1])

# Step 2: Use those indices to sort the entire array
sorted_arr = arr[sort_indices]

print("Sorted array:\n", sorted_arr)

Sorted array:
 [[20  1]
 [30  2]
 [10  3]]


In [26]:
# 91. Find the 50th percentile (median) of a random array.
arr = np.random.rand(10)
percentile = np.percentile(arr, 50)
median = np.median(arr)
print(percentile)
print(median)

0.34138184789162973
0.34138184789162973


In [ ]:
# 92. Find the 25th and 75th percentiles of an array. 
arr = np.random.rand(10)
percentile = np.percentile(arr, [25, 75])
print(percentile)

[0.39540989 0.88639486]


In [28]:
# 93. Find all non-zero elements in the array [1, 0, 2, 0, 3].
arr = np.array([1, 0, 2, 0, 3])
non_zero = np.nonzero(arr)
print(non_zero)

(array([0, 2, 4], dtype=int64),)


In [29]:
# 94. Check which elements of array a are present in array b.

a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6])

# Check which elements of a are in b
mask = np.in1d(a, b)

print("Presence mask:", mask)
print("Matching elements:", a[mask])

Presence mask: [False  True False  True]
Matching elements: [2 4]


In [30]:
# 95. Find the top 3 largest values from a 1D array. 
arr = np.array([5, 1, 9, 3, 7, 2])
top3 = np.sort(arr)[-3:]

print("Top 3 largest values:", top3)

Top 3 largest values: [5 7 9]


In [31]:
top3_indices = np.argpartition(arr, -3)[-3:]
top3_unsorted = arr[top3_indices]

print("Top 3 (unsorted):", top3_unsorted)

Top 3 (unsorted): [5 7 9]


In [32]:
sorted_indices = arr.argsort()[-3:][::-1]
top3_sorted = arr[sorted_indices]

print("Top 3 sorted:", top3_sorted)
print("Indices:", sorted_indices)

Top 3 sorted: [9 7 5]
Indices: [2 4 0]


### Practical Applications (Linear Algebra & I/O) 

In [35]:
# 96. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication.
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
c = np.matmul(A, B)
d = A @ B
print(c)
print(d)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [36]:
# 97. Find the inverse of matrix A. 
A = np.array([[1, 2],
              [3, 4]])

arr = np.linalg.inv(A)
print(arr)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
# 98. Find the determinant of matrix B. 
B = np.array([[5, 6],
              [7, 8]])

arr = np.linalg.det(B)
print(arr)

-1.999999999999999


In [ ]:
# 99. Save a NumPy array to a binary file named my_array.npy. 
my_array = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Save it to a binary file
np.save('my_array.npy', my_array)

In [ ]:
# 100. Load the array from my_array.npy. 
loaded_array = np.load('my_array.npy')

print("Loaded array:\n", loaded_array)

In [38]:
# 101. Save a 2D array to a text file my_matrix.csv with comma-separated values.
my_matrix = np.array([[1, 2, 3],
                      [4, 5, 6]])

# Save to CSV file with comma-separated values
np.savetxt('my_matrix.csv', my_matrix, delimiter=',', fmt='%d') 