### Array creation and attributes using NumPy

In [2]:
# 1. Import the Numpy library with the alias 'np'.
import numpy as np

In [3]:
# 2. Create a 1D numpy array from the python list [1, 2, 3, 4, 5].
array_id = np.array([1, 2, 3, 4, 5])
print(array_id)

[1 2 3 4 5]


In [16]:
# 3. Create a 1D arrays of 10 zeros.
array_zeros = np.zeros(10, dtype=int)
print(array_zeros)

[0 0 0 0 0 0 0 0 0 0]


In [13]:
# 4. Create a 3 x 3 array filled with ones.
array_ones = np.ones((3, 3), dtype=int)
print(array_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# 5. Create an array of all even integers from 10 to 50.
array_even = np.arange(10, 51, 2)
print(array_even)
# arange is as range in python, but return an array.


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [19]:
# 6. Create a 3X3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 7. Create 4x4 identity matrix.
identity_matrix = np.eye(4, dtype=int)
print(identity_matrix)
# np.eye is used to create a 2D array with ones on the diagonal and zeros elsewhere.

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# 8. Create an array of 5 numbers evenly spaced between 0 and 1.
array_linspace = np.linspace(0, 1, 5)
print(array_linspace)
# linspace is used to control number of elements in the array.

[0.   0.25 0.5  0.75 1.  ]


In [23]:
# 9. Create a 3x4 array filled with random numbers between 0 and 1.
random_array = np.random.rand(3, 4)
print(random_array)  

[[0.59188404 0.38132965 0.7508258  0.03925646]
 [0.74829948 0.16012904 0.05715558 0.18332562]
 [0.53103049 0.63440179 0.35763802 0.06007654]]


In [26]:
# 10. Create a 5x5 array with random integers from 1 to 100.
random_array = np.random.randint(1, 101, size=(5, 5))
print(random_array) 

[[96 11 76 16 57]
 [61 43 27 57  2]
 [65 63 21 37 15]
 [86 30 93 88 36]
 [85 34 45 41 46]]


In [28]:
# 11. Given the array arr = np.arange(25).reshape(5, 5), find its shape. 
arr = np.arange(25).reshape(5, 5)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [31]:
# 12. for the same array, find its data type.
print(arr.dtype)

int32


In [32]:
# 13. For the same array arr, find the total number of elements.
print(arr.size)

25


In [33]:
# 14. Create the array [1, 2, 3] but make sure its data type is float. 
array_float = np.array([1, 2, 3], dtype=float)
print(array_float)

[1. 2. 3.]


In [ ]:
# 15. Convert the data type of an existing integer array to float.
array_int = np.array([1, 2, 3, 4, 5])
array_converted = array_int.astype(float)
print(array_converted)

[1. 2. 3. 4. 5.]


### Indexing & Slicing (Accessing Your Data)

In [6]:
arr_1d = np.arange(10)
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# 16. From arr_1d, get the first element.
print(arr_1d[0]) 

0


In [8]:
# 17. From arr_1d, get the last element. 
print(arr_1d[-1])

9


In [9]:
# 18. From arr_1d, get the elements from index 2 up to index 5.
print(arr_1d[2:6]) 

[2 3 4 5]


In [10]:
# 19. From arr_1d, get all elements in reverse order.
print(arr_1d[::-1]) 

[9 8 7 6 5 4 3 2 1 0]


In [11]:
# 20. From arr_2d, get the element at row 1, column 2 (which is 6). 
print(arr_2d[1, 2])

6


In [12]:
# 21. From arr_2d, get the entire first row [1, 2, 3].
print(arr_2d[0]) 

[1 2 3]


In [13]:
# 22. From arr_2d, get the entire second column [2, 5, 8].
print(arr_2d[:, 1])

[2 5 8]


In [14]:
# 23. From arr_2d, extract the sub-array [[1, 2], [4, 5]]. 
print(arr_2d[0:2, 0:2])

[[1 2]
 [4 5]]


In [ ]:
# 24. Create a boolean mask to find all numbers in arr_1d that are greater than 5. 
mask = arr_1d > 5
print(mask)

[6 7 8 9]
[False False False False False False  True  True  True  True]


In [20]:
# 25. Use the boolean mask from the previous question to select the actual numbers from arr_1d. 
print(arr_1d[mask])

[6 7 8 9]


In [21]:
# 26. In one line, select all numbers from arr_2d that are odd.
print(arr_2d[arr_2d % 2 == 1]) 

[1 3 5 7 9]


In [22]:
# 27. In arr_1d, replace all values greater than 5 with the value 0. 
arr_1d[arr_1d > 5] = 0
print(arr_1d)

[0 1 2 3 4 5 0 0 0 0]


In [33]:
# 28. From arr_1d, select the elements at indices 1, 3, and 7.
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(arr_1d[[1, 3, 7]])


[20 40 80]


In [36]:
# 29. From arr_2d, select the first and third rows. 
print(arr_2d[[0, 2], :])

[[1 2 3]
 [7 8 9]]


In [38]:
"""30. What is the difference between a slice (view) and a fancy index (copy)? Modify a slice of 
arr_1d and see if the original changes."""
arr_1d = np.array([10, 20, 30, 40, 50])
slice_arr = arr_1d[1:4]  # This creates a view (slice)
facny_arr = arr_1d[[1, 2, 3]]  # This creates a copy (fancy index)
print("Original array:", arr_1d)
print("Slice (view):", slice_arr)
print("Fancy index (copy):", facny_arr)

Original array: [10 20 30 40 50]
Slice (view): [20 30 40]
Fancy index (copy): [20 30 40]


In [39]:
# 31. Create a copy of arr_2d and modify an element in the copy. Check if the original array is affected.
arr_2d_copy = arr_2d.copy()
arr_2d_copy[0, 0] = 99
print("Original arr_2d:\n", arr_2d)
print("Modified copy of arr_2d:\n", arr_2d_copy) 

Original arr_2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified copy of arr_2d:
 [[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [40]:
# 32. From arr_2d, get the diagonal elements [1, 5, 9]. 
print(np.diag(arr_2d))

[1 5 9]


In [56]:
# 33. Select all rows from arr_2d where the first element is less than 5.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original \n{arr_2d} \n")
print(f"less than < 5  \n{arr_2d[arr_2d[:, 0] < 5]}")

Original 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

less than < 5  
[[1 2 3]
 [4 5 6]]


In [57]:
# 34. From arr_2d, select the elements [2, 4, 9]. 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[[0, 1, 2], [1, 0, 2]])

[2 4 9]


In [58]:
# 35. Reverse the order of the rows in arr_2d.
print(arr_2d[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]
