### Array creation and attributes using NumPy

In [1]:
# 1. Import the Numpy library with the alias 'np'.
import numpy as np

In [3]:
# 2. Create a 1D numpy array from the python list [1, 2, 3, 4, 5].
array_id = np.array([1, 2, 3, 4, 5])
print(array_id)

[1 2 3 4 5]


In [16]:
# 3. Create a 1D arrays of 10 zeros.
array_zeros = np.zeros(10, dtype=int)
print(array_zeros)

[0 0 0 0 0 0 0 0 0 0]


In [13]:
# 4. Create a 3 x 3 array filled with ones.
array_ones = np.ones((3, 3), dtype=int)
print(array_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
# 5. Create an array of all even integers from 10 to 50.
array_even = np.arange(10, 51, 2)
print(array_even)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [19]:
# 6. Create a 3X3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
# 7. Create 4x4 identity matrix.
identity_matrix = np.eye(4, dtype=int)
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [22]:
# 8. Create an array of 5 numbers evenly spaced between 0 and 1.
array_linspace = np.linspace(0, 1, 5)
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
# 9. Create a 3x4 array filled with random numbers between 0 and 1.
random_array = np.random.rand(3, 4)
print(random_array)  

[[0.59188404 0.38132965 0.7508258  0.03925646]
 [0.74829948 0.16012904 0.05715558 0.18332562]
 [0.53103049 0.63440179 0.35763802 0.06007654]]


In [26]:
# 10. Create a 5x5 array with random integers from 1 to 100.
random_array = np.random.randint(1, 101, size=(5, 5))
print(random_array) 

[[96 11 76 16 57]
 [61 43 27 57  2]
 [65 63 21 37 15]
 [86 30 93 88 36]
 [85 34 45 41 46]]


In [28]:
# 11. Given the array arr = np.arange(25).reshape(5, 5), find its shape. 
arr = np.arange(25).reshape(5, 5)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [31]:
# 12. for the same array, find its data type.
print(arr.dtype)

int32


In [32]:
# 13. For the same array arr, find the total number of elements.
print(arr.size)

25


In [33]:
# 14. Create the array [1, 2, 3] but make sure its data type is float. 
array_float = np.array([1, 2, 3], dtype=float)
print(array_float)

[1. 2. 3.]


In [34]:
# 15. Convert the data type of an existing integer array to float.
array_int = np.array([1, 2, 3, 4, 5])
array_converted = array_int.astype(float)
print(array_converted)

[1. 2. 3. 4. 5.]
